# Generated by Django 3.2.6 on 2021-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isSameBillingAddress',
            field=models.BooleanField(default=False),
        ),
    ]
